//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.10 at 07:27:01 PM GMT+05:00 
//


package com.google.code.linkedinapi.schema.impl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.google.code.linkedinapi.schema.Error;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "timestamp",
    "errorCode",
    "message"
})
@XmlRootElement(name = "error")
public class ErrorImpl
    implements Error
{

    @XmlElement(required = true)
    protected BigInteger status;
    @XmlElement(required = true)
    protected BigInteger timestamp;
    @XmlElement(name = "error-code", required = true)
    protected BigInteger errorCode;
    @XmlElement(required = true)
    protected String message;

    public BigInteger getStatus() {
        return status;
    }

    public void setStatus(BigInteger value) {
        this.status = value;
    }

    public BigInteger getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(BigInteger value) {
        this.timestamp = value;
    }

    public BigInteger getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(BigInteger value) {
        this.errorCode = value;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String value) {
        this.message = value;
    }

}
