//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.03 at 12:13:40 PM GMT+05:00 
//


package com.google.code.linkedinapi.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}member-url"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "memberUrl"
})
@XmlRootElement(name = "member-url-resources")
public class MemberUrlResources {

    @XmlElement(name = "member-url", required = true)
    protected MemberUrl memberUrl;

    /**
     * Gets the value of the memberUrl property.
     * 
     * @return
     *     possible object is
     *     {@link MemberUrl }
     *     
     */
    public MemberUrl getMemberUrl() {
        return memberUrl;
    }

    /**
     * Sets the value of the memberUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberUrl }
     *     
     */
    public void setMemberUrl(MemberUrl value) {
        this.memberUrl = value;
    }

}
