//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.03 at 12:13:40 PM GMT+05:00 
//


package com.google.code.linkedinapi.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}network-stats"/>
 *         &lt;element ref="{}updates"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "networkStats",
    "updates"
})
@XmlRootElement(name = "network")
public class Network {

    @XmlElement(name = "network-stats", required = true)
    protected NetworkStats networkStats;
    @XmlElement(required = true)
    protected Updates updates;

    /**
     * Gets the value of the networkStats property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkStats }
     *     
     */
    public NetworkStats getNetworkStats() {
        return networkStats;
    }

    /**
     * Sets the value of the networkStats property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkStats }
     *     
     */
    public void setNetworkStats(NetworkStats value) {
        this.networkStats = value;
    }

    /**
     * Gets the value of the updates property.
     * 
     * @return
     *     possible object is
     *     {@link Updates }
     *     
     */
    public Updates getUpdates() {
        return updates;
    }

    /**
     * Sets the value of the updates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Updates }
     *     
     */
    public void setUpdates(Updates value) {
        this.updates = value;
    }

}
